/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TraineeRecord = IDL.Record({
  'dob' : IDL.Text,
  'theoryMarks' : IDL.Nat,
  'result' : IDL.Text,
  'totalMarks' : IDL.Nat,
  'trade' : IDL.Text,
  'itiName' : IDL.Text,
  'examSystem' : IDL.Text,
  'practicalMarks' : IDL.Nat,
  'annualYear' : IDL.Text,
  'name' : IDL.Text,
  'engDrawingMarks' : IDL.Nat,
  'formativeAssessmentMarks' : IDL.Nat,
  'tradeTheoryMarks' : IDL.Nat,
  'nsqfLevel' : IDL.Text,
  'fatherName' : IDL.Text,
  'workshopCalcMarks' : IDL.Nat,
  'rollNumber' : IDL.Text,
  'tradePracticalMarks' : IDL.Nat,
  'resultDate' : IDL.Text,
  'employabilityMarks' : IDL.Nat,
  'examDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllTrainees' : IDL.Func([], [IDL.Vec(TraineeRecord)], ['query']),
  'searchMarksheet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(TraineeRecord)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TraineeRecord = IDL.Record({
    'dob' : IDL.Text,
    'theoryMarks' : IDL.Nat,
    'result' : IDL.Text,
    'totalMarks' : IDL.Nat,
    'trade' : IDL.Text,
    'itiName' : IDL.Text,
    'examSystem' : IDL.Text,
    'practicalMarks' : IDL.Nat,
    'annualYear' : IDL.Text,
    'name' : IDL.Text,
    'engDrawingMarks' : IDL.Nat,
    'formativeAssessmentMarks' : IDL.Nat,
    'tradeTheoryMarks' : IDL.Nat,
    'nsqfLevel' : IDL.Text,
    'fatherName' : IDL.Text,
    'workshopCalcMarks' : IDL.Nat,
    'rollNumber' : IDL.Text,
    'tradePracticalMarks' : IDL.Nat,
    'resultDate' : IDL.Text,
    'employabilityMarks' : IDL.Nat,
    'examDate' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllTrainees' : IDL.Func([], [IDL.Vec(TraineeRecord)], ['query']),
    'searchMarksheet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(TraineeRecord)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };